### PR TITLE
DM-39193: fixes inheritance of username argument for cm check

### PR DESCRIPTION
**Pull request by villarrealas**

### CODE REVIEW

**Review by eigerx — APPROVED** [review]
Looks great!

**Comment by eacharles** [comment]
Heya Sierra, any concerns that this will interfere with other panda checking functions?On Jul 28, 2023, at 2:23 PM, Sierra Villarreal ***@***.***> wrote:﻿



You can view, comment on, or merge this pull request online at:
  https://github.com/lsst-dm/cm_tools/pull/91

Commit Summary

  43d1a98  added username to checker class for cross-user functionality
  e27637e  fixed inheritance of generic_username value


File Changes  (4 files)

  
    M
    src/lsst/cm/tools/cli/commands.py
    (15)
  
  
    M
    src/lsst/cm/tools/cli/options.py
    (8)
  
  
    M
    src/lsst/cm/tools/core/checker.py
    (2)
  
  
    M
    src/lsst/cm/tools/core/panda_utils.py
    (4)
  


Patch Links:

  https://github.com/lsst-dm/cm_tools/pull/91.patch
  https://github.com/lsst-dm/cm_tools/pull/91.diff

**Comment by eigerx** [comment]
Ooh that is a good question. Should I poke in and test if I can still access your test database as the original pilot?

**Comment by eacharles** [comment]
That makes sense…On Jul 28, 2023, at 4:08 PM, Orion Eiger ***@***.***> wrote:﻿
Ooh that is a good question. Should I poke in and test if I can still access your test database as the original pilot?

**Comment by villarrealas** [comment]
This should not interfere with existing functions (without a username being provided, it defaults to None in all functions, which is the normal behavior). But feel free to test it!

**Pull request merged**
