### PR TITLE
Tickets/dm 38067

### PR DESCRIPTION
**Pull request by eacharles**

### CODE REVIEW

**Review by fritzm — APPROVED** [review]
I get how the config flows in at the campaign level and these template settings have to diffuse down through the insert handler methods to make it out to the workflows, but it seems a bit strange that as a result these columns have to live redundantly at all levels in the database?

In any case, the motto of v1 is "move fast and learn things", so approving this review to go in as is!  (I think we will probably want to tweak the configuration strategy a little for v2 for this and other reasons, and I do already have a ticket in the sprint to scratch my head about that as soon as next week...)

**Comment by eacharles** [comment]
I agree.   

It would probably make more sense to pull all the _shared_ stuff out into a table, and then index into that.

-e

**Comment by eacharles** [comment]
FWIW, pretty sure that SQLAlchemy translates class inheritance into 1) write a table for the parent-class 2) add a table for the sub-class and index into the parent class table, so maybe that is the way to deal with the stuff that shows up at many hierarchy levels.

**Comment by eacharles** [comment]
Then again, I'm worried that asking SQLAlchemy to be clever is a recipe for wondering why your code is so slow.

**Comment by fritzm** [comment]
Yes; I'd say leave it alone for now -- I'll ponder, and we'll address it on the way to v2.

**Pull request merged**
