### PR TITLE
more complicated string processing to avoid misreading pipetask

### PR DESCRIPTION
**Pull request by villarrealas**
I just wrote a better way of processing the jobName that will get pipetask more consistently regardless of formating changes.

### CODE REVIEW

**Review by eigerx — APPROVED** [review]
LGTM!

**Review by eigerx — CHANGES_REQUESTED** [review]
Request though: Can we get pipetask into report-errors? It'd be much more useful if we did.

**Comment by villarrealas** [comment]
Pipetask reporting is added in.

**Review by eigerx — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
