### PR TITLE
Minor changes to get panda-query related command line tasks working

### PR DESCRIPTION
**Pull request by eacharles**
I even made a JIRA ticket and everything.

### CODE REVIEW

**Comment by villarrealas** [comment]
Looks very reasonable to me. Thanks for catching me missing the > 0 in a logic loop. I probably forgot to update that when I wrote the specific i = 1 case.

**Comment by villarrealas** [comment]
Found the issue: jeditaskids that have the aborted status due to a pilot kill command (I believe the only way you get aborted status) do not generate jobs. So when you look for job errors, you find nothing.

Probably should have something in place to handle this.

**Review by fritzm — APPROVED** [review]
Looks good to me

**Review by villarrealas — APPROVED** [review]
Fine for me as a minimal case, we should add TODOs for the specific weird cases though.

**Pull request merged**
